INSERT INTO Color VALUES ('0', 'White')
INSERT INTO Color VALUES ('1', 'Orange')
INSERT INTO Color VALUES ('2', 'Magenta')
INSERT INTO Color VALUES ('3', 'Light Blue')
INSERT INTO Color VALUES ('4', 'Yellow')
INSERT INTO Color VALUES ('5', 'Lime')
INSERT INTO Color VALUES ('6', 'Pink')
INSERT INTO Color VALUES ('7', 'Gray')
INSERT INTO Color VALUES ('8', 'Light Gray')
INSERT INTO Color VALUES ('9', 'Cyan')
INSERT INTO Color VALUES ('10', 'Purple')
INSERT INTO Color VALUES ('11', 'Blue')
INSERT INTO Color VALUES ('12', 'Brown')
INSERT INTO Color VALUES ('13', 'Green')
INSERT INTO Color VALUES ('14', 'Red')
INSERT INTO Color VALUES ('15', 'Black')
--The numbers for IDs are based on in-game Data value