INSERT INTO Pattern VALUES ('bs', 'Base', 'bs.png')
INSERT INTO Pattern VALUES ('ts', 'Chief', 'ts.png')
INSERT INTO Pattern VALUES ('ls', 'Pale dexter', 'ls.png')
INSERT INTO Pattern VALUES ('rs', 'Pale sinister', 'rs.png')
INSERT INTO Pattern VALUES ('cs', 'Pale', 'cs.png')
INSERT INTO Pattern VALUES ('ms', 'Fess', 'ms.png')
INSERT INTO Pattern VALUES ('drs', 'Bend', 'drs	.png')
INSERT INTO Pattern VALUES ('dls', 'Bend sinister', 'dls.png')
INSERT INTO Pattern VALUES ('ss', 'Paly', 'ss.png')
INSERT INTO Pattern VALUES ('cr', 'Saltire', 'cr.png')
INSERT INTO Pattern VALUES ('sc', 'Cross', 'sc.png')
INSERT INTO Pattern VALUES ('ld', 'Per bend sinister', 'ld.png')
INSERT INTO Pattern VALUES ('rud', 'Per bend', 'rud.png')
INSERT INTO Pattern VALUES ('lud', 'Per bend inverted', 'lud.png')
INSERT INTO Pattern VALUES ('rd', 'Per bend sinister inverted', 'rd.png')
INSERT INTO Pattern VALUES ('vh', 'Per pale', 'vh.png')
INSERT INTO Pattern VALUES ('vhr', 'Per pale inverted', 'vhr.png')
INSERT INTO Pattern VALUES ('hh', 'Per fess', 'hh.png')
INSERT INTO Pattern VALUES ('hhb', 'Per fess inverted', 'hhb.png')
INSERT INTO Pattern VALUES ('bl', 'Base dexter canton', 'bl.png')
INSERT INTO Pattern VALUES ('br', 'Base sinister canton', 'br.png')
INSERT INTO Pattern VALUES ('tl', 'Chief dexter canton', 'tl.png')
INSERT INTO Pattern VALUES ('tr', 'Chief sinister canton', 'tr.png')
INSERT INTO Pattern VALUES ('bt', 'Chevron', 'bt.png')
INSERT INTO Pattern VALUES ('tt', 'Inverted chevron', 'tt.png')
INSERT INTO Pattern VALUES ('bts', 'Base indented', 'bts.png')
INSERT INTO Pattern VALUES ('tts', 'Chief indented', 'tts.png')
INSERT INTO Pattern VALUES ('mc', 'Roundel', 'mc.png')
INSERT INTO Pattern VALUES ('mr', 'Lozenge', 'mr.png')
INSERT INTO Pattern VALUES ('bo', 'Bordure', 'bo.png')
INSERT INTO Pattern VALUES ('cbo', 'Bordure indented', 'cbo.png')
INSERT INTO Pattern VALUES ('bri', 'Field masoned', 'bri.png')
INSERT INTO Pattern VALUES ('gra', 'Gradient', 'gra.png')
INSERT INTO Pattern VALUES ('gru', 'Base gradient', 'gru.png')
INSERT INTO Pattern VALUES ('cre', 'Creeper charge', 'cre.png')
INSERT INTO Pattern VALUES ('sku', 'Skull charge', 'sku.png')
INSERT INTO Pattern VALUES ('flo', 'Flower charge', 'flo.png')
INSERT INTO Pattern VALUES ('moj', 'Thing', 'moj.png')
INSERT INTO Pattern VALUES ('glb', 'Globe', 'glb.png')
INSERT INTO Pattern VALUES ('pig', 'Snout', 'pig.png')
