INSERT INTO Category Values ('Flower Charger Pattern')
INSERT INTO Category VALUES ('Creeper Charger Pattern')
INSERT INTO Category Values ('Skull Charger Pattern')
INSERT INTO Category Values ('Thing Pattern')
INSERT INTO Category Values ('Snout Pattern')
INSERT INTO Category Values ('Globe Pattern')
INSERT INTO Category Values ('No Pattern used')
